'use strict';
import { calculateTestEvidence } from '../calculators/calculate_test_evidence.mjs';
import { normalizeSpEaseComponent } from '../calculators/normalize_sp_ease_component.mjs';
import { calculateFileScoreRaw } from '../calculators/calculate_file_score_raw.mjs';
import { calculateFileScoreFinal } from '../calculators/calculate_file_score_final.mjs';
import { calculateSubsystemAggregate } from '../calculators/calculate_subsystem_aggregate.mjs';
import { calculateCapabilityAggregate } from '../calculators/calculate_capability_aggregate.mjs';
import { calculateDeclarationStatus } from '../calculators/calculate_declaration_status.mjs';
import { calculateSemanticScopeStatus } from '../calculators/calculate_semantic_scope_status.mjs';
import { calculateOwnershipCompletenessStatus } from '../calculators/calculate_ownership_completeness_status.mjs';
import { calculateScoreObservabilityStatus } from '../calculators/calculate_score_observability_status.mjs';
import { calculatePublicationStatus } from '../calculators/calculate_publication_status.mjs';
export function buildScoringStage({ capabilityMap, ownership, evidence }) { const files = capabilityMap.capabilities[0].files.map((entry) => { const sp = evidence.spScores.byPath[entry.path] ?? 0; const test = calculateTestEvidence(evidence.fileTestEvidence.records.filter((r) => r.productionFile === entry.path)); const raw = calculateFileScoreRaw({ spTotalScore: sp, testEvidenceScore: test.score ?? 0 }); const ownerState = ownership.rows.find((row) => row.relative === entry.path)?.ownerState || 'UNOWNED'; const final = calculateFileScoreFinal({ spObservable: true, testEvidenceObservable: test.status === 'COMPLETE', ownershipStatus: ownerState, rawScore: raw.raw }); return { path: entry.path, spTotalScore: sp, spEaseComponent: normalizeSpEaseComponent(sp), testEvidence: test, rawFileScore: raw, finalFileScore: final, classification: entry.classification, primaryLayer: entry.primaryLayer || null, semanticContractRule: entry.semanticContractRule, ownerState }; }); const memberFiles = files.filter((f) => f.classification === 'GEOMETRY_MEMBER'); const memberScores = memberFiles.filter((f) => Number.isFinite(f.rawFileScore.raw)).map((f) => f.rawFileScore.raw); const expectedMemberCount = memberFiles.length; const subsystem = calculateSubsystemAggregate(files.map((f) => f.finalFileScore.value).filter(Number.isFinite)); const capability = calculateCapabilityAggregate(memberScores, expectedMemberCount); const declarationStatus = calculateDeclarationStatus({ scopeResolved: true }); const semanticScopeStatus = calculateSemanticScopeStatus({ missing: false, nonexistent: false, duplicates: false, invalid: false }); const ownershipCompletenessStatus = calculateOwnershipCompletenessStatus(ownership.rows); const scoreObservabilityStatus = calculateScoreObservabilityStatus({ count: memberScores.length, partial: memberScores.length > 0 && memberScores.length < expectedMemberCount }); const publicationStatus = calculatePublicationStatus({ semanticScopeStatus, ownershipStatus: ownershipCompletenessStatus, scoreObservabilityStatus, rawScore: capability.raw }); return { files, subsystem, capability, declarationStatus, semanticScopeStatus, ownershipCompletenessStatus, scoreObservabilityStatus, publicationStatus }; }
