'use strict';

(function initCommandRuntimeHandlers(global) {
  const { setStatus } = global.CommandRuntimeShared;

  function dispatchActionMap(action, handlers) { const fn = handlers[action]; if (!fn) return false; fn(); return true; }
  function runNewReport() { if (!confirm('¿Nuevo reporte? Se perderán los cambios no guardados.')) return; DS.setElements([], 'CommandRuntimeHandlers.new'); DS.sections.forEach((s) => { s.height = s.stype === 'det' ? 14 : 60; }); DS.clearSelectionState('CommandRuntimeHandlers.new'); SectionEngine.render(); SelectionEngine.clearSelection(); DS.saveHistory(); }
  function runExportPdf() { FileEngine.exportPDF().catch((error) => alert(`Error al exportar PDF: ${error.message}`)); }
  function runMarginChange(promptText, getter, setter, source) { const v = parseInt(prompt(promptText, getter() || 0)); if (!isNaN(v)) { setter(v, source); applyLayout && applyLayout(); DS.saveHistory(); } }
  function runColorPicker(id, value, format, swatchVar) { const cp = document.getElementById(id); cp.value = value; cp.click(); cp.oninput = (e) => { FormatEngine.applyFormat(format, e.target.value); document.documentElement.style.setProperty(swatchVar, e.target.value); }; }
  function runFormatField() { if (DS.selection.size > 0) PropertiesEngine.render(); document.getElementById('panel-right').scrollTop = 9999; }
  function runColorFont() { const sel = DS.getSelectedElements(); runColorPicker('color-picker-font', sel.length ? sel[0].color : '#000000', 'color', '--swatch-font'); }
  function handleFileCommands(action) { return dispatchActionMap(action, { open() { FileEngine.load(); }, save() { FileEngine.save(); }, 'save-as': () => FileEngine.exportJSON(), 'export-json': () => FileEngine.exportJSON(), 'export-pdf': runExportPdf }); }
  function handlePreviewCommands(action) { return dispatchActionMap(action, { preview: () => _canonicalPreviewWriter().toggle(), 'page-first': () => PreviewEngineRenderer.pageFirst(), 'page-prev': () => PreviewEngineRenderer.pagePrev(), 'page-next': () => PreviewEngineRenderer.pageNext(), 'page-last': () => PreviewEngineRenderer.pageLast() }); }
  function handleZoomCommands(action) { return dispatchActionMap(action, { 'zoom-in': () => ZoomEngine.step(1, 'plus'), 'zoom-out': () => ZoomEngine.step(-1, 'minus'), 'zoom-100': () => ZoomEngine.set(1.0), 'zoom-fit-page': () => CommandEngine.zoomFitPage && CommandEngine.zoomFitPage(), 'zoom-fit-width': () => CommandEngine.zoomFitWidth && CommandEngine.zoomFitWidth() }); }
  function handleSelectionCommands(action) { return dispatchActionMap(action, { undo() { DS.undo(); SectionEngine.render(); SelectionEngine.clearSelection(); }, redo() { DS.redo(); SectionEngine.render(); SelectionEngine.clearSelection(); }, cut() { CommandEngine.cut(); }, copy() { CommandEngine.copy(); }, paste() { CommandEngine.paste(); }, delete() { CommandEngine.delete(); }, 'select-all': () => CommandEngine.selectAll(), 'align-lefts': () => CommandEngine.alignLefts(), 'align-centers': () => CommandEngine.alignCenters(), 'align-rights': () => CommandEngine.alignRights(), 'align-tops': () => CommandEngine.alignTops(), 'align-middles': () => CommandEngine.alignMiddles(), 'align-bottoms': () => CommandEngine.alignBottoms(), 'same-width': () => CommandEngine.sameWidth(), 'same-height': () => CommandEngine.sameHeight(), 'bring-front': () => CommandEngine.bringFront(), 'send-back': () => CommandEngine.sendBack(), 'bring-forward': () => CommandEngine.bringForward && CommandEngine.bringForward(), 'send-backward': () => CommandEngine.sendBackward && CommandEngine.sendBackward(), group: () => CommandEngine.group && CommandEngine.group(), ungroup: () => CommandEngine.ungroup && CommandEngine.ungroup(), 'invert-selection': () => CommandEngine.invertSelection && CommandEngine.invertSelection(), 'lock-object': () => CommandEngine.lockObject && CommandEngine.lockObject(), 'unlock-object': () => CommandEngine.unlockObject && CommandEngine.unlockObject(), 'hide-object': () => CommandEngine.hideObject && CommandEngine.hideObject(), 'show-object': () => CommandEngine.showObject && CommandEngine.showObject(), 'deselect-all': () => { DS.clearSelectionState('CommandRuntimeHandlers.deselectAll'); SelectionEngine.renderHandles && SelectionEngine.renderHandles(); } }); }
  function handleFormatCommands(action) { return dispatchActionMap(action, { 'format-field': runFormatField, 'color-font': runColorFont, 'color-bg': () => runColorPicker('color-picker-bg', '#ffffff', 'bgColor', '--swatch-bg'), 'color-border': () => runColorPicker('color-picker-border', '#000000', 'borderColor', '--swatch-border') }); }
  function handleInsertCommands(action) { return dispatchActionMap(action, { 'insert-text': () => InsertEngine.setTool('text'), 'insert-field': () => InsertEngine.setTool('field'), 'insert-line': () => InsertEngine.setTool('line'), 'insert-box': () => InsertEngine.setTool('box') }); }
  function handleLayoutCommands(action) { return dispatchActionMap(action, { 'toggle-rulers': () => RulerEngine.toggle(), 'add-horizontal-guide': () => CommandEngine.addHGuide && CommandEngine.addHGuide(), 'add-vertical-guide': () => CommandEngine.addVGuide && CommandEngine.addVGuide(), 'remove-guide': () => CommandEngine.removeGuide && CommandEngine.removeGuide(), 'clear-guides': () => AlignmentGuides && AlignmentGuides.clear(), 'set-margin-left': () => runMarginChange('Margen izquierdo (px):', () => DS.pageMarginLeft, (value, source) => DS.setPageMarginLeft(value, source), 'CommandRuntimeHandlers.setMarginLeft'), 'set-margin-right': () => setStatus('Margen derecho: use Configurar página'), 'set-margin-top': () => runMarginChange('Margen superior (px):', () => DS.pageMarginTop, (value, source) => DS.setPageMarginTop(value, source), 'CommandRuntimeHandlers.setMarginTop'), 'set-margin-bottom': () => setStatus('Margen inferior: use Configurar página'), 'insert-section': () => CommandEngine.insertSection && CommandEngine.insertSection(), 'delete-section': () => CommandEngine.deleteSection && CommandEngine.deleteSection(), 'move-section-up': () => CommandEngine.moveSectionUp && CommandEngine.moveSectionUp(), 'move-section-down': () => CommandEngine.moveSectionDown && CommandEngine.moveSectionDown(), 'rename-section': () => CommandEngine.renameSection && CommandEngine.renameSection(), 'toggle-grid': () => { GridEngine.setVisible(!DS.gridVisible); document.getElementById('btn-grid').classList.toggle('active', DS.gridVisible); }, 'toggle-snap': () => { DS.setSnapToGrid(!DS.snapToGrid, 'CommandRuntimeHandlers.toggleSnap'); document.getElementById('btn-snap').classList.toggle('active', DS.snapToGrid); } }); }
  function handleDialogCommands(action) { return dispatchActionMap(action, { new: runNewReport, quit: () => { if (confirm('¿Cerrar ReportForge?')) window.close(); } }); }
  function handleSystemCommands(action) { return dispatchActionMap(action, { print: () => window.print(), refresh: () => setStatus('Datos actualizados') }); }
  function handleAction(action) { if (!action) return; if (handleFileCommands(action)) return; if (handlePreviewCommands(action)) return; if (handleZoomCommands(action)) return; if (handleSelectionCommands(action)) return; if (handleFormatCommands(action)) return; if (handleInsertCommands(action)) return; if (handleLayoutCommands(action)) return; if (handleDialogCommands(action)) return; if (handleSystemCommands(action)) return; }
  function handleToolSelection(tool) { InsertEngine.setTool(tool); }
  function handleViewSelection(view) { if (view === 'preview') { _canonicalPreviewWriter().show(); return; } _canonicalPreviewWriter().hide(); }
  function handleZoomSelection(value, source = 'toolbar-select') { ZoomEngine.set(parseFloat(value) / 100, undefined, undefined, { event: source, fn: 'CommandRuntimeHandlers.handleZoomSelection' }); }
  function handleFormatAction(format) { if (format === 'bold' || format === 'italic' || format === 'underline') { FormatEngine.toggleFormat(format); return; } if (format.startsWith('align-')) { FormatEngine.applyFormat('align', format.replace('align-', '')); } }
  function handleFontFamilyChange(value) { FormatEngine.applyFormat('fontFamily', value); }
  function handleFontSizeChange(value) { FormatEngine.applyFormat('fontSize', parseInt(value)); }

  global.CommandRuntimeHandlers = {
    handleAction,
    handleToolSelection,
    handleViewSelection,
    handleZoomSelection,
    handleFormatAction,
    handleFontFamilyChange,
    handleFontSizeChange,
  };
})(window);
