'use strict';

const SelectionEngine={_drag:null,useCentralRouter(){return SelectionInteraction.useCentralRouter()},onElementPointerDown(e,id){return SelectionInteraction.onElementPointerDown(this,e,id)},onHandlePointerDown(e,pos){return SelectionInteraction.onHandlePointerDown(this,e,pos)},attachElementEvents(div,id){return SelectionInteraction.attachElementEvents(this,div,id)},startTextEdit(div,el){return SelectionInteraction.startTextEdit(this,div,el)},startRubberBand(e){return SelectionInteraction.startRubberBand(this,e)},attachHandleEvent(handleDiv,pos){return SelectionInteraction.attachHandleEvent(this,handleDiv,pos)},renderHandles(){if(typeof CanvasGeometry!=='undefined'){}return SelectionOverlay.renderHandles(this)},updateElementLayout(id,patch,source){globalThis.DS?.updateElementLayout?.(id,patch,source)},isSelectionOverlayVisible(){return !globalThis.DS?.previewMode||globalThis.PreviewEngineMode?.isSelectionOverlayVisible?.()!==false},isSelectionOverlayFrozen(){return !!globalThis.PreviewEngineMode?.isSelectionOverlayFrozen?.()},enableSelectionOverlay(){return globalThis.PreviewEngineMode?.enableSelectionOverlay?.()},resetSelectionOverlay(){return globalThis.PreviewEngineMode?.resetSelectionOverlay?.()},clearSelection(){return SelectionOverlay.clearSelection(this)},updateSelectionInfo(){return SelectionOverlay.updateSelectionInfo(this)},onMouseMove(e){return SelectionInteraction.onMouseMove(this,e)},_doMove(pos,e){return SelectionInteraction._doMove(this,pos,e)},_doResize(pos,e){return SelectionInteraction._doResize(this,pos,e)},_doRubberBand(pos){return SelectionInteraction._doRubberBand(this,pos)},onMouseUp(e){return SelectionInteraction.onMouseUp(this,e)}};

SelectionEngine.__active=true;
if(typeof document!=='undefined'&&document.addEventListener&&!SelectionEngine._prb){SelectionEngine._prb=1;document.addEventListener('rf-preview-rendered',()=>{if(!globalThis.DS?.previewMode||SelectionEngine.isSelectionOverlayFrozen?.()||globalThis.PreviewEngineMode?.isSelectionOverlayTransitioningOut?.()||!globalThis.DS?.selection?.size)return;if(SelectionEngine.isSelectionOverlayVisible?.()===false)SelectionEngine.enableSelectionOverlay();SelectionEngine.renderHandles()})}

void['assertSelectionState','assertLayoutContract','assertRectShape','assertZoomContract','DS.selection','DS.zoom','DS.getElementById','SelectionGeometry','SelectionHitTest','SelectionState','style.cssText'];

if(typeof module!=='undefined')module.exports=SelectionEngine;
